### ISSUE TITLE
Implement Splittable for SslStream

### ISSUE THREAD

**Issue by ForsakenHarmony** [cyderize/rust-websocket#127]
I currently can't run the client example with a secure web socket

```
error: no method named `split` found for type `websocket::Client<openssl::ssl::SslStream<std::net::TcpStream>>` in the current scope
  --> src\main.rs:30:43
   |
30 |   let (mut receiver, mut sender) = client.split().unwrap();
   |                                           ^^^^^
   |
   = note: the method `split` exists but the following trait bounds were not satisfied: `openssl::ssl::SslStream<std::net::TcpStream> : websocket::stream::Splittable`
```

not sure if I'm doing this wrong, but I just use `.connect_secure(None)` instead of `.connect_insecure()`

**Comment by illegalprime** [comment]
@ForsakenHarmony Not implementing `Splittable` for an `SslStream` is correct. The ability to clone SSL streams was deprecated in the `openssl` crate some time ago (and cloning is how this is implemented in `TcpStream` with `.try_clone` ).

That being said the `feat/tokio` branch is almost finished (I have to write the docs for it) and it provides fully asynchronous use of the library which means there you actually _can_ split SSL streams (and much more!). I encourage you to try that branch out:

```toml
[dependencies.websocket]
git = "https://github.com/cyderize/rust-websocket"
branch = "feat/tokio"
```

There are already async versions of all the original examples in that branch, reading those will be pretty helpful in figuring out how to use the new changes. The changes are very comprehensive and large so I'd really like some input on it. Let me know what you think!

**Comment by ForsakenHarmony** [comment]
yeah, that seems to work, but I'm still getting an error with ssl

```
Connecting to wss://echo.websocket.org
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TlsError(Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("unexpected EOF during handshake") }) })', src\libcore\result.rs:859
```

**Comment by illegalprime** [comment]
thanks, I'll take a look at that!

**Comment by ForsakenHarmony** [comment]
that might be a problem on my side, had a "SslHandshakeError" with the old version, but I have no idea how to figure out what exactly it is

**Comment by illegalprime** [comment]
I'm getting something similar, could be related to tokio-rs/tokio-tls#15

**Comment by ForsakenHarmony** [comment]
I'm on windows

here's my full log
```
   Compiling machinelearning v0.1.0 (file:///C:/Users/Me/Code/Rust/machinelearning)
    Finished dev [unoptimized + debuginfo] target(s) in 4.46 secs
     Running `target\debug\machinelearning.exe`
Connecting to wss://echo.websocket.org
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TlsError(Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("unexpected EOF during handshake") }) })', src\libcore\result.rs:859
stack backtrace:
   0:     0x7ff6fbc36c2d - std::sys_common::backtrace::_print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1:     0x7ff6fbc3dd10 - std::panicking::default_hook::{{closure}}
                               at C:\projects\rust\src\libstd\panicking.rs:354
   2:     0x7ff6fbc3d7c0 - std::panicking::default_hook
                               at C:\projects\rust\src\libstd\panicking.rs:371
   3:     0x7ff6fbc3e1e1 - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:549
   4:     0x7ff6fbc3e098 - std::panicking::begin_panic<collections::string::String>
                               at C:\projects\rust\src\libstd\panicking.rs:511
   5:     0x7ff6fbc3dfa1 - std::panicking::begin_panic_fmt
                               at C:\projects\rust\src\libstd\panicking.rs:495
   6:     0x7ff6fbc3df19 - std::panicking::rust_begin_panic
                               at C:\projects\rust\src\libstd\panicking.rs:471
   7:     0x7ff6fbc41767 - core::panicking::panic_fmt
                               at C:\projects\rust\src\libcore\panicking.rs:69
   8:     0x7ff6fbab6597 - core::result::unwrap_failed<websocket::result::WebSocketError>
                               at C:\projects\rust\src\libcore\macros.rs:29
   9:     0x7ff6fbaa46b6 - core::result::Result<(futures::stream::select::Select<futures::stream::filter_map::FilterMap<futures::stream::split::SplitStream<tokio_io::framed::Framed<alloc::boxed::Box<Stream>, websocket::codec::ws::MessageCodec<websocket::message::OwnedMessage>>>, closure>, futures::stream::map_err::MapErr<futures::sync::mpsc::Receiver<websocket::message::OwnedMessage>, closure>>, futures::stream::split::SplitSink<tokio_io::framed::Framed<alloc::boxed::Box<Stream>, websocket::codec::ws::MessageCodec<websocket::message::OwnedMessage>>>), websocket::result::WebSocketError>::unwrap<(futures::stream::select::Select<futures::stream::filter_map::FilterMap<futures::stream::split::SplitStream<tokio_io::framed::Framed<alloc::boxed::Box<Stream>, websocket::codec::ws::MessageCodec<websocket::message::OwnedMessage>>>, closure>, futures::stream::map_err::MapErr<futures::sync::mpsc::Receiver<websocket::message::OwnedMessage>, closure>>, futures::stream::split::SplitSink<tokio_io::framed::Framed<alloc::boxed::Box<Stream>, websocket::codec::ws::MessageCodec<websocket::message::OwnedMessage>>>),websocket::result::WebSocketError>
                               at C:\projects\rust\src\libcore\result.rs:737
  10:     0x7ff6fbad46b6 - machinelearning::main
                               at C:\Users\ArmyOfAnarchists\Code\Rust\machinelearning\src\main.rs:65
  11:     0x7ff6fbc3f0d1 - panic_unwind::__rust_maybe_catch_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  12:     0x7ff6fbc3e4ae - std::rt::lang_start
                               at C:\projects\rust\src\libstd\rt.rs:52
  13:     0x7ff6fbad548b - main
  14:     0x7ff6fbc467e0 - __scrt_common_main_seh
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  15:     0x7ffc75ab8363 - BaseThreadInitThunk
```

**Comment by illegalprime** [comment]
@ForsakenHarmony I fixed it and pushed it to the branch, thanks for catching that!
I also added an `ssl-client.rs` example that you can try out to get the feel of the new API.

**Comment by illegalprime** [comment]
Also your project looks cool, mind if I ask what it's about?

**Comment by ForsakenHarmony** [comment]
trying to use leaf with data from a websocket

**Comment by ForsakenHarmony** [comment]
yeah, it's fixed, thx

**Comment by adrianbrink** [comment]
@illegalprime Is there a timeline on merging feat/tokio into the main branch?

**Comment by illegalprime** [comment]
@adrianbrink It's already merged, you can use tokio _right now_!

**Comment by adrianbrink** [comment]
So I now can split a TslStream?

**Comment by illegalprime** [comment]
@adrianbrink yes if you use the `async` side of the crate
