### ISSUE TITLE
NoSecWsKeyHeader Error

### ISSUE THREAD

**Issue by planet0104** [cyderize/rust-websocket#174]
let server = Server::bind("127.0.0.1:8080", &handle).unwrap();

Use new WebSocket("ws://127.0.0.1:8080"); is OK.

but http://127.0.0.1:8080， server will panik at server.incoming().
How to solve？

> 
> 
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoSecWsKeyHeader', libcore\result.rs:945:5
> stack backtrace:
>    0: std::sys::windows::backtrace::unwind_backtrace
>              at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
>    1: std::sys_common::backtrace::_print
>              at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
>    2: std::sys_common::backtrace::print
>              at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
>    3: std::panicking::default_hook::{{closure}}
>              at C:\projects\rust\src\libstd\panicking.rs:380
>    4: std::panicking::default_hook
>              at C:\projects\rust\src\libstd\panicking.rs:396
>    5: std::panicking::rust_panic_with_hook
>              at C:\projects\rust\src\libstd\panicking.rs:576
>    6: std::panicking::begin_panic<alloc::string::String>
>              at C:\projects\rust\src\libstd\panicking.rs:537
>    7: std::panicking::begin_panic_fmt
>              at C:\projects\rust\src\libstd\panicking.rs:521
>    8: std::panicking::rust_begin_panic
>              at C:\projects\rust\src\libstd\panicking.rs:497
>    9: core::panicking::panic_fmt
>              at C:\projects\rust\src\libcore\panicking.rs:71
>   10: core::result::unwrap_failed<websocket::server::upgrade::HyperIntoWsError>
>              at C:\projects\rust\src\libcore\macros.rs:23
>   11: core::result::Result<(), websocket::server::upgrade::HyperIntoWsError>::unwrap<(),websocket::server::upgrade::HyperIntoWsError>
>              at C:\projects\rust\src\libcore\result.rs:782
>   12: server::main
>              at .\src\main.rs:255
>   13: std::rt::lang_start::{{closure}}<()>
>              at C:\projects\rust\src\libstd\rt.rs:74
>   14: std::rt::lang_start_internal::{{closure}}
>              at C:\projects\rust\src\libstd\rt.rs:59
>   15: std::panicking::try::do_call<closure,i32>
>              at C:\projects\rust\src\libstd\panicking.rs:479
>   16: panic_unwind::__rust_maybe_catch_panic
>              at C:\projects\rust\src\libpanic_unwind\lib.rs:102
>   17: std::panicking::try
>              at C:\projects\rust\src\libstd\panicking.rs:458
>   18: std::panic::catch_unwind
>              at C:\projects\rust\src\libstd\panic.rs:358
>   19: std::rt::lang_start_internal
>              at C:\projects\rust\src\libstd\rt.rs:58
>   20: std::rt::lang_start<()>
>              at C:\projects\rust\src\libstd\rt.rs:74
>   21: main
>   22: invoke_main
>              at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
>   23: __scrt_common_main_seh
>              at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
>   24: BaseThreadInitThunk
>   25: RtlUserThreadStart

**Comment by planet0104** [comment]
i just want Filter out illegal connections
