### ISSUE TITLE
Panic on Request.accept()

### ISSUE THREAD

**Issue by barosl** [cyderize/rust-websocket#21]
I'm getting a panic when accepting a new connection using `Request.accept()` on server, especially when multiple clients are trying to connect at once.

```
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:362
stack backtrace:
   1:     0x7f9cfc9b10f4 - sys::backtrace::write::h9babc8795a85a17910C
   2:     0x7f9cfc9b4c7f - panicking::on_panic::h87037425aaedfce4thJ
   3:     0x7f9cfc9a276a - rt::unwind::begin_unwind_inner::h938edd242c70217e2XI
   4:     0x7f9cfc9a2e21 - rt::unwind::begin_unwind_fmt::h73e2fa758231ca8aDWI
   5:     0x7f9cfc9b4667 - rust_begin_unwind
   6:     0x7f9cfc9e0b64 - panicking::panic_fmt::h4acd4dec7d5ce278Tku
   7:     0x7f9cfc9e09e4 - panicking::panic::he2b07ace86a7d60eqju
   8:     0x7f9cfc91f898 - option::Option<T>::unwrap::h8919241931690594829
                        at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/macros.rs:19
   9:     0x7f9cfc91aede - server::response::Response<R, W>::new::h4627714234374605650
                        at /home/barosl/.cargo/registry/src/github.com-1ecc6299db9ec823/websocket-0.11.2/src/server/response.rs:73
  10:     0x7f9cfc91acd8 - server::request::Request<R, W>::fail::h18318390619043582200
                        at /home/barosl/.cargo/registry/src/github.com-1ecc6299db9ec823/websocket-0.11.2/src/server/request.rs:152
  11:     0x7f9cfc909e78 - server::request::Request<R, W>::accept::h8170096839402963781
                        at /home/barosl/.cargo/registry/src/github.com-1ecc6299db9ec823/websocket-0.11.2/src/server/request.rs:145
  12:     0x7f9cfc8f955e - main::h618e390d4325d3e6maa
                        at src/main.rs:17
  13:     0x7f9cfc9b85d8 - rust_try_inner
  14:     0x7f9cfc9b85c5 - rust_try
  15:     0x7f9cfc9b67cb - rt::lang_start::h5750d73c7867c0b9ecJ
  16:     0x7f9cfc8f99e4 - main
  17:     0x7f9cfbad1ec4 - __libc_start_main
  18:     0x7f9cfc8f9148 - <unknown>
  19:                0x0 - <unknown>
```

The relevant code seems to be:

```rust
    /* src/server/response.rs:71-73 */
    pub fn new(request: Request<R, W>) -> Response<R, W> {
        let mut headers = Headers::new();
        headers.set(WebSocketAccept::new(request.key().unwrap()));
```

**Comment by cyderize** [comment]
Can you please see if the branch 0.11.3 fixes this issue? Hopefully it does.

**Comment by barosl** [comment]
This also seems to be fixed. I'm greatly surprised by your fast response! Great job!
