### ISSUE TITLE
Can't run on 1.1.0-nightly: panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by endel** [cyderize/rust-websocket#33]
I can run both server and client, but when the client starts there is a runtime error:

```
$ cargo run --example server
     Running `target/debug/examples/server`
Connection from 127.0.0.1:58077
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NoDataAvailable', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:729
```

```
$ cargo run --example client
     Running `target/debug/examples/client`
Connecting to ws://127.0.0.1:2794/
thread '<main>' panicked at 'arithmetic operation overflowed', /Users/endel/.cargo/registry/src/github.com-1ecc6299db9ec823/httparse-0.1.1/src/lib.rs:34
```

```
$ rustc --version
rustc 1.1.0-nightly (aecf3d8b6 2015-05-01) (built 2015-05-01)
```

**Comment by cyderize** [comment]
Yes, I've also been getting this error, and it's been a pain to track down since it doesn't seem to originate from this library - it appears to be in one of hyper's dependencies.

I'll continue to look into this

**Comment by endel** [comment]
It's now working, using 1.1.0!
